#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v3
# autospec commit: 750e50d
#
Name     : pypi-pdm_pep517
Version  : 1.1.4
Release  : 24
URL      : https://files.pythonhosted.org/packages/43/42/5c8818b70fc4b25c99e56aeeb3484ede076114c8a0772675b44a3b7891cc/pdm-pep517-1.1.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/43/42/5c8818b70fc4b25c99e56aeeb3484ede076114c8a0772675b44a3b7891cc/pdm-pep517-1.1.4.tar.gz
Summary  : A PEP 517 backend for PDM that supports PEP 621 metadata
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause CC-BY-4.0 ISC MIT
Requires: pypi-pdm_pep517-license = %{version}-%{release}
Requires: pypi-pdm_pep517-python = %{version}-%{release}
Requires: pypi-pdm_pep517-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# PDM-PEP517
**This project has been renamed and re-published as [pdm-backend](https://pypi.org/project/pdm-backend)**

%package license
Summary: license components for the pypi-pdm_pep517 package.
Group: Default

%description license
license components for the pypi-pdm_pep517 package.


%package python
Summary: python components for the pypi-pdm_pep517 package.
Group: Default
Requires: pypi-pdm_pep517-python3 = %{version}-%{release}

%description python
python components for the pypi-pdm_pep517 package.


%package python3
Summary: python3 components for the pypi-pdm_pep517 package.
Group: Default
Requires: python3-core
Provides: pypi(pdm_pep517)

%description python3
python3 components for the pypi-pdm_pep517 package.


%prep
%setup -q -n pdm-pep517-1.1.4
cd %{_builddir}/pdm-pep517-1.1.4
pushd ..
cp -a pdm-pep517-1.1.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707130306
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pdm_pep517
cp %{_builddir}/pdm-pep517-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pdm_pep517/f15bd5033216f10c392e98887c39374601c898ac || :
cp %{_builddir}/pdm-pep517-%{version}/pdm/pep517/_vendor/boolean.py.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-pdm_pep517/b2e6af1d5adfcb019f28053da0e78010b34a8fda || :
cp %{_builddir}/pdm-pep517-%{version}/pdm/pep517/_vendor/cerberus/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pdm_pep517/1887ddf1ee05ccdccdade2ccab4757f2dd1cbb74 || :
cp %{_builddir}/pdm-pep517-%{version}/pdm/pep517/_vendor/license_expression/apache-2.0.LICENSE %{buildroot}/usr/share/package-licenses/pypi-pdm_pep517/2048933452c7fda41ba194b27031d931dd6ddadf || :
cp %{_builddir}/pdm-pep517-%{version}/pdm/pep517/_vendor/license_expression/cc-by-4.0.LICENSE %{buildroot}/usr/share/package-licenses/pypi-pdm_pep517/6e55f0780239c6f263c1ab27a55205efb0204d6d || :
cp %{_builddir}/pdm-pep517-%{version}/pdm/pep517/_vendor/license_expression/data/cc-by-4.0.LICENSE %{buildroot}/usr/share/package-licenses/pypi-pdm_pep517/6e55f0780239c6f263c1ab27a55205efb0204d6d || :
cp %{_builddir}/pdm-pep517-%{version}/pdm/pep517/_vendor/packaging/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/pypi-pdm_pep517/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/pdm-pep517-%{version}/pdm/pep517/_vendor/packaging/LICENSE.BSD %{buildroot}/usr/share/package-licenses/pypi-pdm_pep517/fdc0e4eabc45522b079deff7d03d70528d775dc0 || :
cp %{_builddir}/pdm-pep517-%{version}/pdm/pep517/_vendor/tomli/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pdm_pep517/9da6ca26337a886fb3e8d30efd4aeda623dc9ade || :
cp %{_builddir}/pdm-pep517-%{version}/pdm/pep517/_vendor/tomli_w/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pdm_pep517/9da6ca26337a886fb3e8d30efd4aeda623dc9ade || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pdm_pep517/1887ddf1ee05ccdccdade2ccab4757f2dd1cbb74
/usr/share/package-licenses/pypi-pdm_pep517/2048933452c7fda41ba194b27031d931dd6ddadf
/usr/share/package-licenses/pypi-pdm_pep517/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/pypi-pdm_pep517/6e55f0780239c6f263c1ab27a55205efb0204d6d
/usr/share/package-licenses/pypi-pdm_pep517/9da6ca26337a886fb3e8d30efd4aeda623dc9ade
/usr/share/package-licenses/pypi-pdm_pep517/b2e6af1d5adfcb019f28053da0e78010b34a8fda
/usr/share/package-licenses/pypi-pdm_pep517/f15bd5033216f10c392e98887c39374601c898ac
/usr/share/package-licenses/pypi-pdm_pep517/fdc0e4eabc45522b079deff7d03d70528d775dc0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
